# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='releasedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
