# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbox', '0002_auto_20151214_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='daysago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
